services:
  spring1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring1
    ports:
      - "7070:7070"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MONGO_URI=mongodb://spring1_mongodb:27017/spring1
      - REDIS_HOST=spring1_redis
      - REDIS_PORT=6379
    depends_on:
      - spring1_mongodb
      - spring1_redis
    networks:
      - spring1-network

  spring1_mongodb:
    image: mongo:latest
    container_name: spring1_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - spring1-network

  spring1_redis:
    image: redis:latest
    container_name: spring1_redis
    ports:
      - "6379:6379"
    networks:
      - spring1-network
    volumes:
      - redis-data:/data

volumes:
  mongodb-data:
  redis-data:

networks:
  spring1-network:
    driver: bridge

